### ISSUE TITLE
Image does not load in IOS mobile devices

### ISSUE THREAD

**Issue by artemi8** [MIDA-group/CytoBrowser#137] opened 2021-08-05 05:00 UTC
I hosted Cytobrowser in the server and tried to annotate in **I-Pad**. Image does not load when you click the button _**start a new session**_ or when I tried to open an image in progress session. 

I checked if it had something to do with the OpenSeaDragon(OSD) but OSD seems to work fine with mobile IOS devices. I tested this by creating a dummy viewer and hosted in the server and tried the basic OSD functionalities.

Please advise what might be the issue and and how can I solve this.

**Comment by joakimlindblad** [comment] 2021-08-05 13:28
I am aware that Safari has issues with accessing local files (see e.g., https://ccm.net/faq/36342-safari-how-to-enable-local-file-access). However, this sounds like a different issue (though with similar result) - did I understand correctly that you are serving files from a separate computer?

Does it work if you use a different browser on your I-Pad (Chrome or Firefox)?
- if it does, then it may be some access restriction of the standard browser of the I-pad.

Let me warn you that the interface is not really well functional for a touch based inout yet (issue #77, all support in this direction are appreciated).

**Comment by artemi8** [comment] 2021-08-05 13:46
Yes I am serving files from a separate computer.  Issue remains the same with all the browser in  IOS mobile devices (I-Pads and I-Phones). 
But the interesting thing is it works well on Mac desktop and laptop devices.

Btw UI and other functionalities works perfectly with android tabs and other android touch devices. Even with stylus everything is smooth. This is an amazing project thanks for that!

I doubt **promptCollabSelection** function in collabClient.js is where something happens. Please let me know if you have any idea to find the issue.

**Comment by joakimlindblad** [comment] 2021-08-05 13:54
Interesting. This clearly requires further exploration.
I am currently on vacation so it may not happen immediately, though.

Does it work to use a suitable URL directly to open an image, or do you get an error then? 

And **Thank you for the kind words!**

**Comment by artemi8** [comment] 2021-08-05 14:49
No it doesn't work. Another thing is I could not find any error in the ios chrome console. 

I am trying to debug it and I found that _initOSD function in tmapp.js is never called for some reason. I am looking into it

**Comment by artemi8** [comment] 2021-08-07 18:53
So the problem is **positive lookbehind regular expression** in overlayHandler.js  
`const values = transform.match(/(?<=\(.*)[^\s,]+(?=.*\))/g);`

which is not supported in iOS device browsers and which in turn prevents any function calls in that file due to this error. 

I am trying to find a way around this problem. Any suggestions on this would be helpful. Thank you in advance.

**Comment by artemi8** [comment] 2021-08-07 20:05
I have changed the regular expression from
 `const values = transform.match(/(?<=\(.*)[^\s,]+(?=.*\))/g);` 
to
`const values = transform.match(/[-+]?[0-9]*\.?[0-9]+/g);` 
which is looking for any floating point numbers/integers. This seems to work exactly like the previous regex and solved the problem with iOS browsers.

**Comment by joakimlindblad** [comment] 2021-08-09 21:34
Thanks for nailing this one @artemi8 !
I'm reopening the issue to remind ourselves to actually implement your fix.
@crydell do you have time to take a look at this? I'm not totally confident in the intent of your original regexpr.

**Comment by crydell** [comment] 2021-08-11 10:03
I had a look at it now, I think the proposed solution works as intended, since there don't seem to be any cases in the specification where any transform would accept anything other than a floating point number or an integer. Since this is the only case where a lookbehind regex is used in the clientside code, I went ahead and put up pull request #139 to get this into the master branch.

**Comment by joakimlindblad** [comment] 2021-08-11 11:47
Merged into master. Closing

**Closed by joakimlindblad** 2021-08-11 11:47 UTC
